image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t etl-image:latest .

deploy:
  stage: deploy
  script:
    - docker run --rm etl-image:latest
